### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by v-alje**
Build.Reason:Manual by Alma Jenks
 Build.Url:https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=263441&view=results
 source_repo.branch:master
 source_repo.csvPath:bundlepackages/sqlite-dotnet
 source_repo.url:https://apidrop.visualstudio.com/binaries/_git/mrefconfig

### CODE REVIEW

**Review by smitpatel — APPROVED** [review]
@v-alje - Any reason the PR doesn't have preview build?

**Comment by v-alje** [comment]
@smitpatel Not certain. I'll close and reopen to see if it will trigger.

**Comment by v-alje** [comment]
@smitpatel It looks like this repo is only equipped with one check. The validation doesn't seem to be hooked up. Try having a repo Admin log into OPS and refresh the Webhooks in the settings tab.

**Comment by smitpatel** [comment]
@scottaddie - You are listed as repository owner in OPS portal for this repo. Is this something you know how to fix?

**Pull request merged**
