### PR TITLE
WIP: See also

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by bricelam** [comment]
@v-alje Can we enable CI on this repo so we can preview changes?

**Comment by v-alje** [comment]
@bricelam file a request here: https://aka.ms/publish-on-docs/reference and we can run the CI job to pick up changes from NuGet packages.

**Comment by bricelam** [comment]
@v-alje I think you misunderstood. This *isn't* being picked up from the NuGet package, so I'm manually adding it here and would like to render a preview to make sure it's going to work.

**Comment by v-alje** [comment]
@bricelam Preview builds are enabled in this repo. 

I'm not an Admin to the repo either.

Please be aware that any manual changes you make to the ECMAXML in this repo, other than the namespace files, are likely to be overwritten the next time the NuGet packages are processed.

**Comment by bricelam** [comment]
I'm frustrated by how unapproachable this repo is. Are product teams expected to do work here? Where do I see preview builds of my branch? Where can I file issues on the thing that would overwrite my manual changes? (If it did this for me, I wouldn't be making these changes.) Are there any additional docs on how the API publish pipeline works or how I can build it locally?

**Comment by v-alje** [comment]
@bricelam No. Product teams are not expected to do work in this repo, except to change namespace XML, and change landing pages. This repo is just storage for the generated ECMAXML used by the Docs build system to build .NET API reference. 

We can set up the CI job that generates the ECMAXML to pick up an unlisted NuGet package from a specified NuGet feed, if you file a request here: https://aka.ms/publish-on-docs/reference and provide the feed.

Issues with the generated .NET API reference can be filed here: https://sitehelp.microsoft.com/

For information on testing the doc generation locally, see: https://review.docs.microsoft.com/en-us/help/onboard/admin/reference/dotnet/testing-locally?branch=main

**Pull request closed without merging**
